const AllsolutionData = [
    {
        id: 1,
        img: "./yuvim/Picture8.jpg",
        logo: "logo2.png",
        noofrating:323,
        user1rating:5,
        url: "https://www.youtube.com/watch?v=Q1MSpaFq0Fw",
        title: 'Los Angeles, CA',
        description: 'Los Angeles, CA',
        attributes: ["Famous for carved into the hillside with the world-famous Hollywood Sign appearing far off in the distance. ", "It hosts countless concerts each year with operas, orchestras and musicals also taking place on its hallowed stage."],
        price: '$12',
        priceDesc: 'Starting at $12 per month',
        LeftPane3: [{ "title": "Landing/URL Page Bookings", "paragraphs": [" Let clients book appointments, view upcoming  ", "appointments, send messages and share files ",] },],
        LeftPane2: [{ "title": "Facebook Bookings", "paragraphs": ["Add a Call-to-Action button to your Facebook page,", " enabling prospects and clients to schedule, book, or take  ", " other actions directly from Facebook"] },],
        LeftPane1: [{ "title": "Website Bookings", "paragraphs": [" Add our online scheduling widget to your site. Allow clients ", "to complete their scheduling process without leaving your", "website. "] },],
        pricings1: [{ "value": 12, "prevalue": "Essentials: $", "postvalue": "Per Month", content: ["Appointment scheduling interface ", " Web and mobile access  ", "Business calendar "] }],
        pricings2: [{ "value": 35, "prevalue": "Premium: $", "postvalue": "Per Month", content: ["All Essentials features +  ", "SMS notifications & reminders ",] }],
        pricings3: [{ "value": 49, "prevalue": "Premium: $", "postvalue": "Per Month", content: ["All Premium features +  ", "Branded interface ", "Customize email templates & notification schemes"] }],
        selectedPricing: null,
        likes: "65",
        doubleflag:0,
        flag:1,
        rating: 5,
        inCart: false,
        action: 'add',
        tags: ['reachcustomers', 'operatebetter', 'reduceexpenses', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]
    },
    {
        id: 8,
        img: "./yuvim/Picture1.jpg",
        logo: "adrabbit.png ",
        url:"https://www.youtube.com/watch?v=dpBollRR-tg",
        title: 'San Diego, CA',
        description: 'San Diego, CA',
        attributes: [" SEAWORLD is the leading tourist attraction in San Diego and one of the most popular marine-life parks in the world ", "Popular attractions include the world-famous San Diego Zoo and San Diego Zoo Safari Park and LEGOLAND California"],
        price: '$17',
        priceDesc: 'Starting at $17 per month',
        LeftPane3: [{ "title": "", "paragraphs": [""," "," "] },],
        LeftPane2: [{ "title": "", "paragraphs": ["","","","" ,""," "] },],
        LeftPane1: [{ "title": "", "paragraphs": [ ] },],
        pricings1: [{ "value": 0 , "prevalue": "Free trail: $", "postvalue": "for 7 days", content: [] }],
        pricings2: [{ "value": 17, "prevalue": "Billed every 6 months: $", "postvalue": "per month", content: [] }],
        pricings3: [{ "value": 25, "prevalue": "Billed monthly:$", "postvalue": "per month", content: [] }],
        noofrating:"",
        user1rating:4,
        flag:1,
        doubleflag:1,
        selectedPricing: null,
        likes: "150",
        inCart: false,
        rating: "5",
        action: 'add',
        tags: ['reachcustomers', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
                ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
              ]

    },
    {
        id: 14,
        img: "./yuvim/Picture2.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'London, UK',
        description: 'London, UK',
        attributes: ["The Tower of London and Westminster neighbour local pubs and markets. It’s a place where travellers can time-hop through the city, and when they’re weary, do as Londoners do and grab a “cuppa” tea"],
        price: '$79',
        priceDesc: 'Starting at $79 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Financial control", "paragraphs": ["Robust financial control solutions can help increase efficiency and accuracy, mitigate risk and meet regulations:", " Accounting services " ,"Bookkeeping services"," Controller services"] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "65",
        inCart: false,
        rating: "4",
        action: 'add',
        tags: ['reachcustomers','operatebetter', 'reduceexpenses','expandbusiness', 'protectbusiness', 'justme', 'lessthan10', 'lessthan50','lessthan500','morethan500', 'All', 'onlinedigi', 'saledigi','nodigi','basicdigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
       ]


    },
    {
        id: 3,
        img: "./yuvim/Picture3.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'Delhi',
        description: 'Delhi',
        attributes: ["Delhi is famous for a lot of things, besides being the national capital. Some of them being: Gardens like The Garden of Five senses, Lodhi Garden, Nehru Park. Taj Mahal one of the world wonder is near to Delhi located in Agra"],
        price: '$2',
        priceDesc: '$2 per approved verification',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Identity check", "paragraphs": [ "Defeat fraud while processing customers data quickly and securly", "Improve  customer experience in the identity verification process using the latest AI & biometric technologies." ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        inCart: false,
        rating: "3.6",
        action: 'add',
        tags: ['protectbusiness', 'lessthan500', 'morethan500', 'All', 'saledigi',
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'     
        ]
    },
    {
        id: 4,
        img: "./yuvim/Picture4.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'Melbourne',
        description: 'Melbourne',
        attributes: ["The vibrant coastal capital of Victoria Colourful, lively Melbourne has broad appeal for every type of traveller, from cosy cafes to local art to Australian and Aboriginal history to spectator sports"],
        price: '$99',
        priceDesc: 'Starting at $99 per hour',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Data and Cloud", "paragraphs": [ "Stop throwing most needed capital on hardware and IT services, pay as you go only for what you actually need:", " Dedicated secured storage of essential data & files of any type.", "Access to all data anytime anywhere"] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        inCart: false,
        rating: "2.6",
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'expandbusiness', 'protectbusiness', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 5,
        img: "./yuvim/Picture5.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'Paris, France',
        description: 'Paris, France',
        attributes: ["Nowhere else on earth makes the heart swoon like the mention of Paris. The city lures with its magnificent art, architecture, culture, and cuisine",],
        price: '$350',
        priceDesc: 'Starting at $350 for 10 hours per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Human Resource", "paragraphs": [" End-to-end service solutions to all Human resource and recruitment needs through a self-serving cloud-based system.", " On going HR experts support over phone, email or chat ",  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        inCart: false,
        rating: "2.8",
        action: 'add',
        tags: ['reachcustomers','operatebetter','reduceexpenses','protectbusiness', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500','morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 6,
        img: "./yuvim/Picture6.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'San Francisco, CA',
        description: 'San Francisco, CA',
        attributes: [" It is home to people of all background and cultures which greatly influence its art, food, fitness, fashion and museums", "The city is known for its great shopping districts. From Union Square with big names to outlets from boutiques to vintage clothes and markets.",],
        price: '$9.90',
        priceDesc: 'Starting at $9.90 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Website Creation", "paragraphs": [ " Create and maintain high-end web site that will make your business stand out.", " Leverage 100s of unique templates, use unlimited pages and get top-grade hosting for free."  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        inCart: false,
        action: 'add',
        rating: "3.6",
        tags: ['reachcustomers', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'All', 'nodigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 7,
        img: "./yuvim/Picture7.jpg",
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        title: 'Amsterdam, Netherlands',
        description: 'Amsterdam, Netherlands',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Law", "paragraphs": [" Quick and professional service for all the legal needs of your business, when you need them, e.g: ", " Non-Disclosure Agreements (NDA) ", " LLC Operating Agreement"  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        attributes: [" From its picturesque canals and bridges to its historic homes, Amsterdam is a full-blown fairytale. The brightly-coloured bicycles and tulip stands around town don’t hurt either. Must-see sights include the Anne Frank House, the Van Gogh Museum",],
        price: '$40',
        priceDesc: 'Starting at $40 per document',
        likes: "150",
        rating: "1",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'protectbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'All', 'basicdigi', 'onlinedigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]


    },

    {
        id: 9,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture9.jpg",
        rating: "2.2",
        title: 'New York City',
        description: 'New York City',
        attributes: ["A trip to New York is worth the expenditure of time and money if you set realistic expectations, but probably not if you're expecting your life to be changed!",],
        price: '$14',
        priceDesc: 'only $14 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "New York City", "paragraphs": [ "Every business needs a mobile app!", " Get one built for your business in no time, make it available to your customers and leverage it to acquire new ones ",  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        inCart: false,
        action: 'add',
        tags: ['reachcustomers', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'All', 'nodigi', 'basicdigi', 'onlinedigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]
    },
    {
        id: 10,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture10.jpg",
        title: 'Perth',
        description: 'Perth',
        attributes: [" Perched on the banks of the wide Swan River, between the Indian Ocean and the sands of the Nullarbour Desert, Perth is one of the world's most isolated cities, yet still boasts an active beach scene and smokin’ nightlife", ],
        price: '',
        priceDesc: ' Let us tailor the best offerfor your business needs',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Data Intelligence", "paragraphs": [ " Harness the power of data to improve you business daily operation and over all performance.", ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        rating: "2.8",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'expandbusiness', 'lessthan500', 'morethan500', 'All', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 11,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture16.jpg",
        title: 'Bangalore',
        description: 'Bangalore',
        attributes: ["It is famous for IT hub in India, Bangalore Palace, Tipu Sultan's Summer Palace, Lal Bagh Botanical Gardens, Nandi Hills, Cubbon Park, National Gallery Of Modern Art, Ulsoor Lake and Government Museum.", ],
        price: '$69',
        priceDesc: 'Starting at $69 per month ',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Workplace Management", "paragraphs": [ "Best tools for managing the ongoing operations and  maintenance of the workplace  environment", "Keep employees happy", "Ensuring overall facilities to management",  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        rating: "3.6",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi',
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 12,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture13.jpg",
        title: 'Hyderabad',
        description: 'Hyderabad',
        attributes: ["Want a taste of being royal? Eat in Hyderabad, where culinary traditions have been passed down from the Nizam monarchy. Arabic, Turkish and Mughlai influences are easily recognisable. The city is famous for its rich, aromatic biryani made with love", ],
        price: '$12',
        priceDesc: 'Starting at $12 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Queue Managemnt", "paragraphs": [ "Automated queue management system ", "Improves your business by managing customers", "Waiting experience of customers is managed throughout their journey", ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        rating: "3.6",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'basicdigi', 'onlinedigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },

    {
        id: 13,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture12.jpg",
        title: 'Canberra',
        description: 'Canberra',
        attributes: ["You can fit a lot into a visit to Australia’s capital city. Surrounded by nature parks, Canberra is best known for a vast collection of history and culture that provides a snapshot of the nation. "],
        price: '',
        priceDesc: 'Let us tailor the best offers for your business need',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "IOT", "paragraphs": [ "Internet Of Things", "Control the best IOT platform for your business", "Seamless integrations,smooth onboardings and easy to use control panes" ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        inCart: false,
        rating: "4.2",
        action: 'add',
        tags: ['protectbusiness', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]


    },
    {
        id: 2,
        logo: "logo1.png",
        noofrating:393,
        user1rating:4,
        img: "./yuvim/Picture14.jpg",
        title: 'Las Vegas',
        mainheading: "Las Vegas",
        url: "https://youtu.be/c0gBAuhlvTU",
        LeftPane3: [{ "title": "Ready Made Content", "paragraphs": ["Images, texts ads & social posts, tailored to your business.", "Update new and fresh readymade content daily to make  ", "sure you have what you need to succeed!"] },],
        LeftPane2: [{ "title": "Social Media", "paragraphs": ["Schedule your posts & engage with your social community.", "A simple easy-to-use post scheduler “set it and forget it” approach for all your  ", "Social pages to save you time logging in over and over, and over again."] },],
        LeftPane1: [{ "title": "web presence", "paragraphs": ["Your business online. Everywhere & on every device. ", "Readymade designs and widgets. Just apply and customize ", "your content to achieve your business objectives."] },],
        pricings1: [{ "value": 9, "prevalue": "Basic: $", "postvalue": "Per Month", content: ["Template based web site & mobile app ", "Social Media Management", "Social Media Content Bank"] }],
        pricings2: [{ "value": 15, "prevalue": "Standard: $", "postvalue": "Per Month", content: ["All Basic features + ", "Online leads collection & management",] }],
        pricings3: [{ "value": 75, "prevalue": "Premium: $", "postvalue": "Per Month", content: ["All Standard features + ", "Marketing specialist support, 2 hours per week"] }],
        description: 'Online & Social Presence',
        attributes: ["Las Vegas is an internationally renowned major resort city, known primarily for its gambling, shopping, fine dining, entertainment, and nightlife",],
        price: '$9',
        selectedPricing: null,
        flag:1,
        doubleflag:0,
        priceDesc: 'Starting at $9 per month',
        likes: "65",
        rating: "5",
        inCart: false,

        action: 'add',
        tags:['reachcustomers','expandbusiness','justme','lessthan10','lessthan50','nodigi','operatebetter','reduceexpenses','protectbusiness','All','lessthan500','morethan500','basicdigi','onlinedigi','saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]


    },
    {
        id: 15,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture15.jpg",
        images:"picture15",
        title: 'Brisbane',
        description: 'Brisbane',
        attributes: ["Australia’s third-largest city, Brisbane is the hub of Queensland culture, offering a peek at the past and a glimpse into the future. "],
        price: '$19',
        priceDesc: 'Starting at $19 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Cyber Security", "paragraphs": ["Are you safe? Access and optimize your business cyber security posture", "Find out your security gaps in minutes", "Get recommendations to resolve issues and avoid further risks"  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        rating: "3.4",
        inCart: false,
        action: 'add',
        tags: ['protectbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]
    },
    {
        id: 16,
        logo: "download.png",
        url:"https://youtu.be/8qsKH3bYVnA",
        img: "./yuvim/Picture11.jpg",
        images:"picture16",
        title: 'Phoenix, AZ',
        description: 'Phoenix, AZ',
        attributes: ["Phoenix offers some of the best Mexican food this side of the border, a number of fine museums, a vibrant artist community and 300 days of sunshine",],
        price: '$33',
        priceDesc: 'Starts at $33 per hour',
        LeftPane3: [{ "title": "Our top-notch graphic designers have the knowledge, experience and skills needed in order to make your business stand out and create engaging and immersive experiences  ", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": ["Logo design and business identity","Banners, ads and landing pages.","Brochures, menus and other printed matters","Creative concepts, prototypes and redesigns","Exhibition stands and posters"] },],
        LeftPane1: [{ "title": ["All the graphic design services modern successful","businesses require.","From a fresh logo, trough a website rebranding to"," print that still catches the eye in the digital age: " ] , "paragraphs": [] },],
        pricings1: [{ "value": 300, "prevalue": "Starter package: $", "postvalue": "", content: ["5 hours with a graphic designer","Suitable for logo design, brochures, posters and","similar one-time design task"] }],
        pricings2: [{ "value": 2500, "prevalue": "One-time project: $", "postvalue": "", content: ["50 hours with our design team ","Suitable for large scale projects such as busines"," rebranding, e-commerce site uplift or app design "] }],
        pricings3: [{ "value": 990, "prevalue": "Retainer: $", "postvalue": "Per month", content: [ "Up to 30 hour per month covering everything a","small business needs " ] }],
        noofrating:"",
        user1rating:3,
        likes: "45",
        flag:1,
        doubleflag:0,
        rating: "5",
        inCart: false,
        action: 'add',
        tags: ['reachcustomers', 'reduceexpenses', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 17,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture17.jpg",
        title: 'Chennai',
        description: 'Chennai',
        attributes: ["Treat your senses to some of the richest South Indian flavours in traditional dishes like sambar, rasam, fish curry or kootu. And don't forget to have a cup of full-bodied Tamil coffee, enhanced with chicory—no visit is complete without it.",],
        price: '$9.90',
        priceDesc: 'Starting at $9.90 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Leads Generation", "paragraphs": [ "Turn your online channel into a client generating powerhouse.", "Address and greet your visitors in a dynamic and appealing way", "Drive conversations and boost sales", ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        likes: "150",
        flag:0,
        doubleflag:0,
        rating: "2.5",
        inCart: false,
        action: 'add',
        tags: ['reachcustomers', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 18,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture18.jpg",
        title: 'Goa',
        description: 'Goa',
        attributes: ["The beaches have long served as a magnet for serene hedonists. To the north, the tourist-centric scene is prevalent, with an international flair that is now skewing more hip than hippie. Travel south for stretches of unspoiled sand and an escape from large resorts",],
        price: '$8',
        priceDesc: 'Starting at $8 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Project Managemnt", "paragraphs": [ "The project management software that will work for your team", "Manage simple to complex project and everything between in one simple and easy tool",  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        rating: "3.5",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'expandbusiness', 'lessthan50', 'lessthan500', 'All', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 19,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture19.jpg",
        title: 'Kochi',
        description: 'Kochi',
        attributes: ["The region is a major banana-growing area, and traditional Kochi cuisine employs the fruit in many dishes, both sweet and savoury. Coconut water provides a refreshing and sweet contrast to the piquant food", ],
        price:'',
        priceDesc: 'Let us tailor best offers for your business needs',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Work From Home", "paragraphs": [ "Work from solutions which fits your needs and provide benifits to your employees and business", "Operational flexibility,lower attrition,enhanced productivity and more.", ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        rating: "4",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]


    },
    {
        id: 20,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture20.jpg",
        title: 'Cairns',
        description: 'Cairns',
        attributes: ["Cairns is the perfect place for passionate divers, adrenaline junkies, and after dark revelers, offering heart-pounding adventure and a booming nightlife scene in a vibrant, tropical setting"],
        price: '$75',
        priceDesc: 'Starting at $75 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Video Surveillance", "paragraphs": [" Let us host the hardware and software of your video-based security systems in the cloud.", "you can access your cameras from any where and any time.","Apply video analytics to identify risks in real time."  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "65",
        rating: "2.8",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'protectbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]


    },
    {
        id: 21,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/pondicherry.jpg",
        title: 'Pondicherry',
        description: 'Pondicherry',
        attributes: ["Blossoming bougainvilleas, crumbling cathedrals on leafy boulevards and 18th-century colonial buildings colour the former French colony of Pondy, which sits on the Bay of Bengal. ",],
        price: '$95',
        priceDesc: 'Starting at $95 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Logistics Process", "paragraphs": ["Meet your logistics requirements in a timely, cost-effective manner.", "Simply plan and execute the efficient transportation, storage and delivery of goods, providing services and more ",] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        rating: "4.4",
        inCart: false,
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'expandbusiness', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]
    },
    {
        id: 22,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture22.jpg",
        title: 'Auckland',
        description: 'Auckland',
        attributes: ["The Māori call Auckland Tāmaki Makaurau — a maiden desired by 100 lovers, and a valuable territory fought over for centuries for its fertile land and natural harbours on the Pacific Ocean (to the east) and Tasman Sea (to the west)."],
        price: '$42',
        priceDesc: 'Starting at $42 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Virtual Workspace", "paragraphs": ["Your employees (and optionally customers or partners) to digitally connected.", " Bridge the separation between them with an array of tools designed to foster close communication and collaboration "  ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "45",
        inCart: false,
        rating: "3.2",
        action: 'add',
        tags: ['operatebetter', 'reduceexpenses', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 23,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture23.jpg",
        title: 'Miami, FL',
        description: 'Miami, FL',
        attributes: ["Miami is famous for its pristine beaches, non-stop nightlife, and fantastic warm weather. Miami is also known for its mind-blowing skyline, luxurious shopping malls, Art Deco architecture, and high-end hotels",],
        price: '$29',
        priceDesc: 'Starting at $29 per month',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "Marketing Automation", "paragraphs": [ "Store,manage and label your leads,contacts and clients in a centralized online hub.", "Segment,target and promote in an automated hassel free way.",   ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        inCart: false,
        rating: "4.5",
        action: 'add',
        tags: ['reachcustomers', 'reduceexpenses', 'expandbusiness', 'justme', 'lessthan10', 'lessthan50', 'lessthan500', 'morethan500', 'All', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },
    {
        id: 24,
        logo: "",
        url:"https://www.youtube.com/watch?v=pL0JXS1wbCM",
        img: "./yuvim/Picture24.jpg",
        title: 'Queensland',
        description: 'Queensland',
        attributes: ["Staggering beauty and heart-pumping thrills await in the resort town of Queenstown, which is also known for its Hobbits—much of the Lord of the Rings trilogy was filmed in the area."],
        price: '$300',
        priceDesc: 'Starting at $300 per year',
        LeftPane3: [{ "title": "", "paragraphs": [] },],
        LeftPane2: [{ "title": "", "paragraphs": [] },],
        LeftPane1: [{ "title": "    Environment Monitoring", "paragraphs": [ " An all-in-one environmental solution for air quality, radiation, virus spread and more.", " A comprehensive sensing solution and a cloud-based software for environmental data analysis " ] },],
        pricings1: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings2: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        pricings3: [{ "value": "", "prevalue": "", "postvalue": "", content: [] }],
        noofrating:"",
        user1rating:"",
        flag:0,
        doubleflag:0,
        likes: "150",
        inCart: false,
        rating: "1.6",
        action: 'add',
        tags: ['protectbusiness', 'lessthan500', 'morethan500', 'All', 'nodigi', 'basicdigi', 'onlinedigi', 'saledigi'
        ,'ad/mar','agriculture','arts/entertainment','automotive','beauty','commercial','education','finanleg','food','tour','medi','nonpro','realesta','Techee','shopreta','sportsrecr','travtra','others'
    ]

    },




];

export default AllsolutionData;
